# Generated by Django 5.1.4 on 2025-02-10 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Detail', models.TextField()),
                ('Location', models.TextField()),
                ('Slot', models.IntegerField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Prize', models.IntegerField()),
            ],
        ),
    ]
