# Generated by Django 5.1.4 on 2025-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Desc', models.TextField()),
                ('Duration', models.CharField(max_length=255)),
                ('Mode', models.CharField(max_length=255)),
                ('Fees', models.IntegerField()),
                ('Certifiction', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=5)),
            ],
        ),
    ]
